"""drohneneinheiten

Revision ID: c610af27d089
Revises: e2ceaef6caed
Create Date: 2026-07-23 15:20:34.250547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c610af27d089'
down_revision = 'e2ceaef6caed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Hinweis: wie schon in ad2f3b109171/e2ceaef6caed -- Autogenerate schlägt erneut das Droppen der
    # DJI-Alttabellen vor, bewusst nicht übernommen (s. docs/roadmap.md "Zwischenschritt -- DJI-
    # FlightHub-2-Integration komplett entfernt").
    op.create_table('units',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unit_managers',
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('unit_id', 'user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_unit_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'units', ['home_unit_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('home_unit_id')

    op.drop_table('unit_managers')
    op.drop_table('units')
    # ### end Alembic commands ###
