"""rc devices

Revision ID: e2ceaef6caed
Revises: ad2f3b109171
Create Date: 2026-07-23 14:50:39.392721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2ceaef6caed'
down_revision = 'ad2f3b109171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Hinweis: wie schon in ad2f3b109171 -- Autogenerate schlägt erneut das Droppen der DJI-Alttabellen
    # vor, bewusst nicht übernommen (s. docs/roadmap.md "Zwischenschritt -- DJI-FlightHub-2-Integration
    # komplett entfernt").
    op.create_table('rc_devices',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('device_key_hash', sa.String(length=255), nullable=False),
    sa.Column('required_qualification', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('paired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rc_devices')
    # ### end Alembic commands ###
